name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          path: __tests__/data/Example.xcresult
          title: Example test report
      - uses: ./
        with:
          path: __tests__/data/Example.xcresult
          title: Example Failures Only test report
          show-passed-tests: false
      - uses: ./
        with:
          path: __tests__/data/KeychainAccess.xcresult
          title: KeychainAccess Failures Only test report
          show-passed-tests: false
      - uses: ./
        with:
          path: __tests__/data/KeychainAccess.xcresult
          title: KeychainAccess test report
      - uses: ./
        with:
          path: __tests__/data/TAU.xcresult
          title: TAU test report
      - uses: ./
        with:
          path: __tests__/data/TestResults.xcresult
          title: TestResults test report
      - uses: ./
        with:
          path: __tests__/data/Coverage.xcresult
          title: Coverage test report
      - uses: ./
        with:
          path: __tests__/data/Coverage.xcresult
          title: Hide Coverage test report
          show-code-coverage: false
      - uses: ./
        with:
          path: __tests__/data/UhooiPicBook.xcresult
          title: UhooiPicBook test report
      - uses: ./
        with:
          path: __tests__/data/UhooiPicBook.xcresult
          title: UhooiPicBook No Passed test report
          show-passed-tests: false
      - uses: ./
        with:
          path: __tests__/data/UhooiPicBook.xcresult
          title: UhooiPicBook No Code Coverage test report
          show-code-coverage: false
      - uses: ./
        with:
          path: |
            __tests__/data/Example.xcresult
            __tests__/data/KeychainAccess.xcresult
            __tests__/data/TAU.xcresult
          title: 'Multiple Paths'
